#!/bin/bash

exec 2>&1 

# formatting python files
black *.py

if [ $? -ne 0 ]; then
    echo "ERROR: Format python files correctly"
    exit 1
fi

# formatting javascript files
js-beautify *.js
if [ $? -ne 0 ]; then
    echo "ERROR: Format javascript files correctly"
    exit 1
fi


